### ISSUE TITLE
default jwtsecret does not match default geth jwt secret. 

### ISSUE THREAD

**Issue by tuxes3** [dappnode/DAppNodePackage-prysm#107]
**Describe the bug**

Newly installed Dappnode setup with GETH and Prysm do not speak with each other as default `jwtsecret` is false in the `beacon-node` implementation. 

**To Reproduce**

1. Install GETH
2. Install Prysm
3. See your Geth jwtsecret in the dappnode gui
4. See the jwtsecret loaded from this repository 
5. They are the same exept the last char is different. 

**Expected behavior**

1. Both keys are the same.

**Screenshots**

NONE

**DAppNode version:**

Core DAppNode Packages versions
bind.dnp.dappnode.eth: 0.2.6
core.dnp.dappnode.eth: 0.2.64
dappmanager.dnp.dappnode.eth: 0.2.59, commit: 26522964
https.dnp.dappnode.eth: 0.1.4
ipfs.dnp.dappnode.eth: 0.2.18
wifi.dnp.dappnode.eth: 0.2.8
wireguard.dnp.dappnode.eth: 0.1.2
System info
dockerComposeVersion: 2.5.0
dockerServerVersion: 20.10.6
dockerCliVersion: 20.10.6
os: debian
versionCodename: bullseye
architecture: amd64
kernel: 5.10.0-19-amd64
Disk usage: 50%

**Additional context**
It works when changing the `jwtsecret` manually on the `beacon-node` container. On updating it, it will fallback to the wrong key again. 

This file needs to end with `5`: https://github.com/dappnode/DAppNodePackage-prysm/blob/main/beacon-chain/jwtsecret.hex and not `8`.

**Comment by eduadiez** [comment]
did you use the stakersUI to configure it? http://my.dappnode/#/stakers/ethereum
the jwtsecret ending in 5 is the default, so I would say that it has not been configured correctly through stakersui, and that is why you do not have the correct jwtsecret in geth. You should see something like this on your geth package config:

<img width="2330" alt="Screenshot 2022-12-25 at 13 29 55" src="https://user-images.githubusercontent.com/20141918/209467947-2649b4cd-cb48-44ba-a70a-835ae6ed649c.png">

**Comment by tuxes3** [comment]
I did configure it trough the stakersUI. There are no `jwtsecret` options there (also in your screenshot I see nothing `jwtsecret` related). 

Is it an `EXTRA_OPTION` you are referring to I might have not seen in the documentation? 

Furthermore with the dappnode setup this should work as seamless as possible as it is marketed for non technical users. The default values should work without having to do configuration. I also do not think having it default is too big of a security risk as everything is behind the VPN.

**Comment by eduadiez** [comment]
> I did configure it trough the stakersUI. There are no jwtsecret options there (also in your screenshot I see nothing jwtsecret related)

This is automatically configured with the selection made in the stakersUI, it is not facilitated to the user to select it to avoid configuration problems.

> Is it an EXTRA_OPTION you are referring to I might have not seen in the documentation?

it is not necessary to modify the extra_opts, unless you want to customize some of the parameters, but this is not the usual use case

> Furthermore with the dappnode setup this should work as seamless as possible as it is marketed for non technical users. The default values should work without having to do configuration. I also do not think having it default is too big of a security risk as everything is behind the VPN.

yes, totally, in no case should it be necessary to modify manully anything that we are discussing here. Simply through the stakersUI you should not have any problem and everything should be configured automatically.

we use several jwt to avoid that several consensus clients connect to the same execution, so we use different jwt for each selected configuration. In future versions we are to include a middleware that allows to connect several simultaneously.

I just did a configuration from scratch, and everything seems to work fine.  Could it be that when overwriting the jwt it no longer behaves as expected?

When you restart your geth package you should see something like this: 
```
Using prysm.dnp.dappnode.eth
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
INFO [12-25|16:40:41.211] Starting Geth on Ethereum mainnet... 
INFO [12-25|16:40:41.212] Bumping default cache on mainnet         provided=1024 updated=4096
```

this means that it will use the jwt defined for prysm: 
https://github.com/dappnode/DAppNodePackage-geth/blob/master/entrypoint.sh#L6
https://github.com/dappnode/DAppNodePackage-geth/blob/master/security/prysm/jwtsecret.hex

Will only use the jwt ending in 5 in case the value of _DAPPNODE_GLOBAL_CONSENSUS_CLIENT_MAINNET (which is set when a selection is made in the stakersUI) is empty or does not correspond to one of the allowed clients

**Comment by tuxes3** [comment]
Ok, now I understand how it should work. Thank you very much for all the informations (especially looking at the date!).

In my GETH config tab I am missing the `_DAPPNODE_GLOBAL_CONSENSUS_CLIENT_MAINNET` config. When I first got the server running, I firstly activated GETH, and only after GETH was running I installed prysm via the StakersUI. 

I guess because I installed it this custom way, the wrong `jwtsecret` is set in the GETH package?

As I dont really want to reboot the prod GETH container without need (I have multiple validators running), what would be the safest approach to get this running like it should, so that the next prysm update does not involve worrying about `jwtsecret` value?

Thanks again and Happy Holidays!

**Comment by tuxes3** [comment]
Any updates?

**Comment by tuxes3** [comment]
Any updates?

**Comment by dsimog01** [comment]
Hey @tuxes3! As Edu said, you should not need to do anything like that with the config. The `_DAPPNODE_GLOBAL_CONSENSUS_CLIENT_MAINNET` is missing because you did not hit on show advanced config I believe. Also, this value should be automatically set after you click on Geth and Prysm in the stakers tab and hit "Apply changes". You should not need to worry about updates because the config will persist. I am closing this issue now as there seems to be no bug, but you can reach me for further details in the #support channel of our discord sever (@dsdiegosg is my nickname).
