### ISSUE TITLE
Account List page headers do not sort correctly after changing number of validators shown

### ISSUE THREAD

**Issue by JHGrove3** [dappnode/DAppNodePackage-prysm#22]
**Describe the bug**
This bug is on the page "Your Validator Accounts List"
http://prysm.dappnode/dashboard/wallet/accounts

The page features a table showing all the validators, with columns for Account Name, Validating Public Key, Validator Index, ETH Balance, Eth Effective Balance, Activation Epoch, Exit Epoch, Status, and Actions.

Upon coming to the page, the table of validators appears to be unsorted. There appears to be a loose sort where the validators with lower index numbers are higher in the list, but they are not all sorted correctly.

Each column header on the page (with the exception of Validating Public Key and Actions) has a rollover feature. When you roll over the title, an arrow appears, implying that you can sort the table by that column. The arrows point up or down. As you click them they swap up vs down sorts.

You can click the arrows and it sorts the validators that are on screen. This defaults to 5 validators every time you come to the page, but you can change the default number.  Note that it only sorts the 5 that are already on the page. If there are more validators not shown, they are not included in the sort.

If you have more than 5 validators, then you need to change the "Items per page" dropdown to show them.

But when you change the Items per Page dropdown, the sort feature stops working. Even if you change it back to 5, the sort feature still will not work. The only way to restore the sort feature is to reload the page.

**To Reproduce**

Open Prysm with an instance that has more than 5 validators running
Go to the Account List page
Try sorting the columns, and see that it works for the 5 validators that are shown.
Change the "Items per Page" to a higher number, like 10
The table updates to show up to 10 validators
Try sorting the table. The table will no longer sort.
Change "Items per Page" back to 5
Try sorting the table. The table STILL will not sort
Reload the page, either with the Refresh button (which may require re-logging in) or by going to the home page, then returning to the Account List page.
Try sorting the table. The sort will once again work for the 5 validators shown

**Expected behavior**

**Screenshots**

**DAppNode version:**

Core DAppNode Packages versions

    bind.dnp.dappnode.eth: 0.2.6
    dappmanager.dnp.dappnode.eth: 0.2.38, commit: 85e2b4cf
    ipfs.dnp.dappnode.eth: 0.2.14
    vpn.dnp.dappnode.eth: 0.2.8, commit: f9a8743e
    wifi.dnp.dappnode.eth: 0.2.6

System info

    docker version: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
    docker compose version: docker-compose version 1.25.5, build unknown
    platform: linux, x64, 5.10.0-2-amd64
    Disk usage: 26%

Prysm verion 1.0.8 (v1.2.2 upstream)

- OS: Built from ISO image 42 - Debian, running on Intel NUC similar to Dappnode Advanced -- NUC10I7FNH1
- Browser 

**Additional context**

**Comment by dapplion** [comment]
Hi @JHGrove3 ! Thanks for detailed feedback, tho we can't make changes to the UI. Would you mind opening a new issue with the same contents to https://github.com/prysmaticlabs/prysm-web-ui/issues ?
