### ISSUE TITLE
Have the "Items per Page" drop downs remember the last selection

### ISSUE THREAD

**Issue by JHGrove3** [dappnode/DAppNodePackage-prysm#23]
**Is your feature request related to a problem? Please describe.**

There are two drop downs labeled "Items per Page" in the Prysm app
One is on the Validator Gains and Losses page: 
http://prysm.dappnode/dashboard/gains-and-losses

The other is on the Validator Accounts List page:
http://prysm.dappnode/dashboard/wallet/accounts

When coming to these pages, both dropdowns always default to 5.  If you have 6 or more validators, you always have to change the dropdown to a higher number in order to see them all.

**Describe the solution you'd like**

I would like the drop down to remember what you chose the last time you visited the page, and default to that number when you return to the page.

**Describe alternatives you've considered**

You could also have a setting in the app, where you indicate what you want to default value to be when you visit the page.

**Additional context**

This is also an issue on the Prysm Pyrmont app.

Note that separately I just entered a bug report that when you change the "Items per Page" dropdown on the Accounts List page, it breaks the sorting feature on that page.

**Comment by dapplion** [comment]
Hi @JHGrove3 ! Thanks for detailed feedback, tho we can't make changes to the UI. Would you mind opening a new issue with the same contents to https://github.com/prysmaticlabs/prysm-web-ui/issues ?
