### ISSUE TITLE
Implement Json Web Token

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodePackage-prysm#52]
The upcoming new release of Prysm will entail a JSON Web Token in the UI that must be sent to the dappmanager so the user must use it in the first login. The data sent must contain the URL to be used in the first login so the dappmanager recognizes it and render it as a URL.

### TODO
- [ ] Add a beauty explanation in the `getting-started.yml`, `dappnode_package.json` (in the description) or in both about how and when to use this URL
- [ ] Build and send the URL with the JWT to the dappmanager in the `entrypoint.sh` taking as reference the code from https://github.com/dappnode/DAppNodePackage-prysm-prater/tree/pablo/test-ui

**Comment by dsimog01** [comment]
Alrady handled via Stakers UI
