### ISSUE TITLE
Package still links to UI

### ISSUE THREAD

**Issue by gnidan** [dappnode/DAppNodePackage-prysm#86]
**Describe the bug**

Since this package switched to using web3-signer, it's no longer possible to use the Prysm web interface, since that interface relies on having local access to signing rights.

Unfortunately, this took me (and perhaps others) quite a bit of time to figure out, since there's still a link to the "UI" and a listed token URL, as seen in the screenshot below.

After spending way too much time trying different URLs (`validator.prysm.dappnode`? `validator.prysm.dappnode:3500`? etc.), I looked in Discord and found a conclusive answer that web3-signer means the web UI is no longer usable.

These links should probably be removed, possibly with a note for users who have upgraded, to inform them that DMS is how best to view validator stats these days.

**To Reproduce**

1. Install latest DNP

**Expected behavior**

I should see no links that reference the web UI. I should see information about how to access information about my validator(s) performance.

**Screenshots**

<img width="1130" alt="Screen Shot 2022-08-19 at 3 06 01 PM" src="https://user-images.githubusercontent.com/151065/185689700-da463d3e-1740-481d-979b-aa4941a8a0db.png">

**DAppNode version:**

**Core DAppNode Packages versions**
bind.dnp.dappnode.eth: 0.2.6
core.dnp.dappnode.eth: 0.2.57
dappmanager.dnp.dappnode.eth: 0.2.52, commit: c7c74340
https.dnp.dappnode.eth: 0.1.3
ipfs.dnp.dappnode.eth: 0.2.17
vpn.dnp.dappnode.eth: 0.2.8, commit: f9a8743e
wifi.dnp.dappnode.eth: 0.2.8
wireguard.dnp.dappnode.eth: 0.1.1

**System info**
dockerComposeVersion: 1.25.5
dockerServerVersion: 20.10.2
dockerCliVersion: 20.10.2
os: debian
versionCodename: bullseye
architecture: amd64
kernel: 5.9.0-1-amd64
Disk usage: 54%
**Additional context**

**Comment by devin-b** [comment]
This could have saved me a bunch of time.

**Comment by MeganerdNL** [comment]
There was a new update, but this is not fixed. Link is still there in 2.0.1

**Comment by alexpeterson91** [comment]
all of the info was included and is still included in every single release since the change.  you had to manually click through a warning page explaining the change. for every release since.
<img width="1655" alt="Screen Shot 2022-09-14 at 4 41 10 AM" src="https://user-images.githubusercontent.com/4649787/190121180-51ce4c03-f3b5-4045-a70a-e75122feb3ca.png">

  It's also been in the Getting Started section with links directly to it since July 13th.  The UI link in the next release coming out in a couple hours is now updated to reflect it as well.

**Comment by pablomendezroyo** [comment]
We should find a way to remove it, so users do not have to manually remove it

**Comment by Pol-Lanski** [comment]
It should lead you to the web3signer UI. @tropicar please fix ASAP.
